<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="tap_to_install_version">Tap to install version %1$s</string>
    <string name="back_content_desc">Back</string>
    <string name="settings_title">Settings</string>
    <string name="changelog">Changelog</string>
    <string name="installing_system_update">Installing system\nupdate…</string>
    <string name="making_update_ready">Making Update ready, this may take a while</string>
    <string name="your_app_getting_better">Your App is getting even better…</string>
    <string name="update_includes_features">This update includes new features and the latest from NexaMusic %1$s, making your app even more helpful. Learn more at %2$s.</string>
    <string name="whats_new">What\'s new?</string>
    <string name="update_available">Update</string>
    <string name="checking_for_updates">Checking for updates…</string>
    <string name="cant_check_updates">Can\'t check for\nupdates</string>
    <string name="app_up_to_date">App is up to date</string>
    <string name="version">Version %1$s</string>
    <string name="released">Released: %1$s</string>
    <string name="update_preview">Update preview</string>
    <string name="downloading_percent">Downloading… %1$d%%</string>
    <string name="download_failed">Download Failed</string>
    <string name="new_features_include">New features include:</string>
    <string name="mobile_network_warning">Downloading updates over a mobile network or while roaming may cause additional charges.</string>
    <string name="update_size">Update size: %1$s MB</string>
    <string name="check_internet_connection">Check your internet connection and try again.</string>
    <string name="vivi_music_version">NEXAMUSIC version %1$s</string>
    <string name="last_checked">Last checked: %1$s</string>
    <string name="install">Install</string>
    <string name="check_for_update">Check for update</string>
    <string name="no_changelog_available">No changelog available</string>
    <string name="system_update">System update</string>
    <string name="app_updates_title">App Updates</string>
    <string name="update_settings_title">Update Settings</string>
    <string name="app_updates_subtitle">App updates</string>
    <string name="app_update_uptodate">Up to date</string>
    <string name="auto_update_check">Automatic update check</string>
    <string name="auto_update_check_subtitle">Automatically check for updates when opening the update screen</string>
    <string name="update_notifications">Update Notifications</string>
    <string name="update_notifications_subtitle">Show a notification when a new update is found</string>
    <string name="settings_check_updates_title">Check for updates</string>
    <string name="later">Later</string>

    <string name="vivi_music_title">NEXAMUSIC</string>
    <string name="developer_section">DEVELOPER</string>
    <string name="collaborator_section">COLLABORATOR</string>
    <string name="app_info_section">APP INFO</string>
    <string name="community_section">COMMUNITY</string>
    <string name="developer_name">Nkosana Mahungela</string>
    <string name="app_developer">Lead Developer</string>
    <string name="website">Website</string>
</resources>